name: Verify CHANGELOG updated

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'
      - '**/*'

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure CHANGELOG.md is updated
      run: |
        if ! git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'CHANGELOG.md'; then
          echo "ERROR: Please update the CHANGELOG.md file with your changes." && exit 1
        fi
